### ISSUE TITLE
[Firefox] Toolbar icon context menu is missing the extension title at the top

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/firefox-bridge#59]
**Description:**
The context menu opened by right clicking the toolbar icon is missing the extension title at the top. See the attached screenshot for more details.

**Steps to reproduce:**
1. Load the Firefox Firefox Bridge v0.1 in the browser
2. Open the extension panel and right click the extension
3. Notice that the context menu is missing the extension title at the top of the context menu

**Expected:**
The context menu should list the extension name at the top, as in the case of the Chromium extension.

**Actual:**
The extension title is not displayed at the top of the context menu.

![2024-02-16_14h11_22](https://github.com/mozilla/firefox-launch/assets/50236075/20c588eb-c18c-4430-b2f5-b4724694d4c0)

**Comment by GregSherman** [comment]
Confirmed this is not a requirement.
