### ISSUE TITLE
[Chromium][Vivaldi] “Firefox Bridge” entry at top of toolbar button context menu is clickable and redirects to non-existent page

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/firefox-bridge#69]
Description:
Opening the toolbar button context menu reveals a “Firefox Bridge” entry at the top that is clickable (as opposed to a non-clickable entry in the case of Chrome or Edge) which redirects to a non existing page on the CWS - https://chrome.google.com/webstore/detail/abbmnijehafopegbcgkeopadgoknaoaf (the last part being the add-on ID).

Steps to reproduce:
1. Load the Chromium Firefox Bridge v0.1 in the browser
2. Right click the toolbar button to open the context menu
3. Notice a clickable “Firefox Bridge” entry at the top of the context menu
4. Click the entry
5. Observe the users is redirected to a non-existent page on CWS - https://chrome.google.com/webstore/detail/abbmnijehafopegbcgkeopadgoknaoaf

Expected:
1. As in the case of Chrome or Edge the entry should be non-clickable/disabled
OR
2. The entry should remain clickable but ensure it redirects to the proper CWS add-on page i.e. add the correct URL to the entry one the extension is on CWS

Actual:
The “Firefox Bridge” entry at the top of the context menu is clickable and redirects to a non-existent CWS page

![2024-02-19_16h07_29](https://github.com/mozilla/firefox-launch/assets/50236075/4625aeb4-85f8-4fd8-ae91-1c6f1cbd98d8)

**Comment by GregSherman** [comment]
closed as Vivaldi is no longer planned for support
