### ISSUE TITLE
[Chromium][Vivaldi] Right click context menu options (open page and link in Firefox – but not Firefox Private Browsing) are available in the toolbar button context menu. “Open link in Firefox” does not work

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/firefox-bridge#70]
Description:
The toolbar button context menu contains 2 of the right click context menu options – “Open page in Firefox” and “Open link in Firefox”. It does, however, not contain the same options for opening pages and links in Firefox Private Browsing.
The “Open page in Firefox” option does work and opens the page in Firefox, whereas the “Open link in Firefox” does not, as the option is not invoked on a link.

Steps to reproduce:
1. Load the Chromium Firefox Bridge v0.1 in the browser
2. Access https://www.wikipedia.org/ in a tab
3. Right click the toolbar button to open the context menu
4. Notice the 2 right click context menu options (“Open page in Firefox” and “Open link in Firefox”) below the “Firefox Bridge” entry. Also notice the corresponding Firefox Private Browsing options are missing
5. Click both options
6. Observe that only the “Open page in Firefox” works

Expected:
Remove the options to make the experience similar to what occurs in Chrome or Edge i.e. no right click context menu options in the toolbar button context menu

Actual:
Right click context menu options are present in the toolbar button context menu, but only “Open page in Firefox” actually works.

![2024-02-19_16h19_09](https://github.com/mozilla/firefox-launch/assets/50236075/1b3b20aa-069c-47e8-84f2-374c314c3ec9)

**Comment by GregSherman** [comment]
closed as Vivaldi is no longer planned for support

**Comment by GregSherman** [comment]
closed as Vivaldi is no longer planned for support
