### ISSUE TITLE
[Chromium][Vivaldi] Check mark for “Always use Firefox Private Browsing” is not displayed

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/firefox-bridge#71]
Description:
The “Always use Firefox Private Browsing” check mark is not displayed in the context menu.

Steps to reproduce:
1. Load the Chromium Firefox Bridge v0.1 in the browser
2. On the welcome page toggle the “
Always open sites in a Firefox Private window when switching”
3. Open the toolbar button context menu
4. Notice that the “Always use Firefox Private Browsing” check mark is not displayed

Expected:
The “Always use Firefox Private Browsing” check mark should be displayed to signal users the state of the option.

Actual:
The check mark for “Always use Firefox Private Browsing” is not displayed in the toolbar button context menu.

![2024-02-19_16h24_19](https://github.com/mozilla/firefox-launch/assets/50236075/ab372c11-e67a-4196-8fbf-761d38a0f1b3)

**Comment by GregSherman** [comment]
closed as Vivaldi is no longer planned for support
