### ISSUE TITLE
[Chromium][Vivaldi] Missing entries in toolbar button context menu (Extension Settings and possibly the permissions options entry)

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/firefox-bridge#72]
Description:
The tollbar button context menu has two missing entries, which from a comparison with Chrome and Edge, might be the “Extension Settings” and possibly the permissions options for the extension.

Steps to reproduce:
1. Load the Chromium Firefox Bridge v0.1 in the browser
2. Open the toolbar button context menu
3. Notice 2 empty entries which can still be focused but when clicked do nothing

Expected:
The “Extension Settings” entry and possibly the permissions options for the extension should be displayed in the context menu.

Actual:
There are two missing entries in the toolbar button context menu - the “Extension Settings” and possibly the permissions options for the extension entries.

![2024-02-19_16h46_49](https://github.com/mozilla/firefox-launch/assets/50236075/b3025c42-3dd9-46f4-b441-267ebc260ff2)

**Comment by GregSherman** [comment]
closed as Vivaldi is no longer planned for support
