### ISSUE TITLE
[Chromium][Vivaldi] “Activate extension” shortcut does not work

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/firefox-bridge#73]
Description:
Trying to use the “Activate extension” shortcut, even though a key combination has been set for it, does not work.

Steps to reproduce:
1. Load the Chromium Firefox Bridge v0.1 in the browser
2. Set a key combination for the “Activate extension” shortcut
3. Access https://www.wikipedia.org/ 
4. Attempt to use the previously set shortcut
5. Notice the shortcut does not work i.e. it does not open the page in Firefox

Expected:
The shortcut for the “Activate extension” action should work.

Actual:
The shortcut for the “Activate extension” action does not work.

**Comment by GregSherman** [comment]
closed as Vivaldi is no longer planned for support
