### ISSUE TITLE
[Chromium][Vivaldi] Toolbar button is not disabled when on privileged or ftp:// pages

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/firefox-bridge#74]
Description:
The toolbar button is not disabled when on privileged pages or on pages with the ftp:// scheme.

Steps to reproduce:
1. Load the Chromium Firefox Bridge v0.1 in the browser
2. Access https://www.wikipedia.org/
3. Notice the toolbar icon is enabled, as expected
4. Access vivaldi://extensions/ which is a privileged page
5. Notice the toolbar icon is still enabled. It should have a disabled appearance
6. Access https://www.mmnt.ru/ftp-sites/ftp.bis.de and right click the ftp://ftp.bis.de/ URL at the top of the page and open it in a new tab. The page has a ftp:// scheme.
7. Notice the toolbar icon is still enabled here as well. It also should have a disabled appearance.

Expected:
The toolbar icon should have a disabled appearance on privileged and ftp:// pages.

Actual:
The toolbar icon does not have a disabled appearance on privileged and ftp:// pages.

https://github.com/mozilla/firefox-launch/assets/50236075/605a44a7-e2f1-4688-8032-bcbc4267c228

**Comment by GregSherman** [comment]
closed as Vivaldi is no longer planned for support
