### ISSUE TITLE
[Chromium][Opera] Toolbar icon context menu is missing the extension title at the top

### ISSUE THREAD

**Issue by acornestean** [mozilla-extensions/firefox-bridge#76]
Description:
The context menu opened by right clicking the toolbar icon is missing the extension title at the top. See the attached screenshot for more details.

Steps to reproduce:
1. Load the Firefox Firefox Bridge v0.1 in the browser
2. Right click the toolbar icon to open the context menu
3. Notice that the context menu is missing the extension title at the top of the context menu

Expected:
The context menu should list the extension name at the top, as in the case of Chrome or Edge, etc.

Actual:
The extension title is not displayed at the top of the context menu.

![2024-02-21_11h10_34](https://github.com/mozilla/firefox-launch/assets/50236075/8476222d-3f41-42e7-b85f-08972a4585f6)

**Comment by GregSherman** [comment]
Confirmed this is not a requirement.
